site/config/routes.rb
# -*- encoding : utf-8 -*-
Teenstar::Application.routes.draw do

  root :to => "pages#index"

  match 'products', :to => 'products#index', :as => "products"  
  #match 'promotions', :to => 'products#promotions', :as => "products"

  namespace :admin do
    resources :reports, :only => [:index, :show] do
      collection do
        get :safety_stock
        get :sales_total
      end
    end
  end
    
end

site/app/views/admin/shared/_address.html.erb
<p>
  <%="#{address.firstname} #{address.lastname} (#{address.phone}" %><%= address.alternative_phone unless address.alternative_phone.blank? %>)<br />
  <%= address.address1 %> <%= ", #{address.address2}" unless address.address2.blank? %>
  <%= ", #{address.city}, #{address.state_text}, #{address.zipcode}, #{address.country.name}" %>
</p>

site/app/views/admin/shared/_address_form.html.erb
<table class="index">
  <thead>
    <tr>
      <th colspan="8">
        <%= name %>
        <span class="right">
          <% if use_billing %>
            <%= check_box_tag 'order[use_billing]', '1', (!(@order.bill_address.empty? && @order.ship_address.empty?) && @order.bill_address.eql?(@order.ship_address)) %> <%= t("use_billing_address") %>
          <% end %>
        </span>
      </th>
    </tr>
  </thead>
  <tbody id="<%= name == t('shipping_address') ? "shipping" : "billing" %>" style="display:<%= (use_billing && (!(@order.bill_address.empty? && @order.ship_address.empty?) && @order.bill_address.eql?(@order.ship_address))) ? "none" : "" %>">
    <tr class="<%= name == t('shipping_address') ? "shipping-row" : "billing-row" %>">
      <td class="lbl-col">
        <%= f.label :firstname, t(:first_name)+':' %>
      </td>
      <td class="val-col" colspan="3"><%= f.text_field :firstname %></td>
      <td class="lbl-col">
        <%= f.label :lastname, t(:last_name)+':' %>
      </td>
      <td class="val-col" colspan="3"><%= f.text_field :lastname %></td>
    </tr>
    <tr class="<%= name == t('shipping_address') ? "shipping-row" : "billing-row" %>">
      <td class="lbl-col">
        <%= f.label :address1, t(:street_address)+':' %>
      </td>
      <td colspan="3"><%= f.text_field :address1, :class => "fullwidth" %></td>
      <td class="lbl-col">
        <%= f.label :address2, t(:street_address_2)+':' %>
      </td>
      <td colspan="3"><%= f.text_field :address2, :class => "fullwidth" %></td>
    </tr>
    <tr class="<%= name == t('shipping_address') ? "shipping-row" : "billing-row" %>">
      <td class="lbl-col">
        <%= f.label :city, t(:city)+':' %>
      </td>
      <td colspan="3"><%= f.text_field :city %></td>
      <td class="lbl-col">
        <%= f.label :zipcode, t(:zip)+':' %>
      </td>
      <td colspan="3"><%= f.text_field :zipcode, :style => "width:100px;" %></td>
    </tr>
    <tr class="<%= name == t('shipping_address') ? "shipping-row" : "billing-row" %>">
      <td class="lbl-col">
        <%= f.label :state_id, t(:state)+':' %>
      </td>
      <td colspan="3">
        <span id="<%= name==t('shipping_address') ? "s" : "b" %>state">

          <%= f.text_field :state_name, :style => "width:150px;display:#{f.object.country.states.empty? ? 'block' : 'none' };", :disabled => !f.object.country.states.empty? %>
          <%= f.collection_select :state_id, f.object.country.states.sort, :id, :name, {:include_blank => true}, {:style=> "width:150px;display:#{f.object.country.states.empty? ? 'none' : 'block' };", :disabled => f.object.country.states.empty?} %>
        </span>
      </td>
      <td class="lbl-col">
        <%= f.label :country_id, t(:country)+':' %>
      </td>
      <td colspan="3">
        <span id="<%= name==t('shipping_address') ? "s" : "b" %>country"><%= f.collection_select :country_id, available_countries, :id, :name, {}, {:style => 'width:150px;'} %></span>
      </td>
    </tr>
    <tr class="<%= name == t('shipping_address') ? "shipping-row" : "billing-row" %>">
      <td class="lbl-col">
        <%= f.label :phone, t(:phone)+':' %>
      </td>
      <td colspan="7"><%= f.text_field :phone %></td>
    </tr>
  </tbody>
</table>

<% content_for :head do %>
  <%= javascript_include_tag '/states', 'admin/address_states' %>
  <script type="text/javascript">
    jQuery(document).ready(function(){
      $('span#<%= name==t('shipping_address') ? "s" : "b" %>country select').change(function() { update_state('<%= name==t('shipping_address') ? "s" : "b" %>'); });
    });
  </script>
<% end %>

site/app/views/admin/shared/_calculator_fields.html.erb
<fieldset id="calculator_fields">
  <legend><%= t('calculator') %></legend>
  <div id="preference-settings">
    <p>
      <%= f.label(:calc_type, t("calculator"), :for => "calc-type") %>
      <%= f.collection_select(:calculator_type, @calculators, :to_s, :description, {}, {:id => "calc-type"}) %>
    </p>
    <% if !@object.new_record? %>
      <div class="calculator-settings">
        <%= f.fields_for :calculator do |calculator_form| %>
          <%= preference_fields(@object.calculator, calculator_form) %>
        <% end %>
      </div>
      <% if @object.calculator.respond_to?(:preferences) %>
        <div id="calculator-settings-warning"><%= t('calculator_settings_warning')%></div>
      <% end %>
    <% end %>
  </div>
</fieldset>

site/app/views/admin/shared/_configuration_menu.html.erb
<% content_for :sidebar do %>

  <h3><%= t("configurations") %></h3>
  <br class="clear" />

  <ul class="sidebar">
    <%= hook :admin_configurations_sidebar_menu do %>
    <li<%== ' class="active"' if controller.controller_name == 'general_settings' %>><%= link_to t("general_settings"), admin_general_settings_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'mail_methods' %>><%= link_to t("mail_methods"), admin_mail_methods_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'tax_categories' %>><%= link_to t("tax_categories"), admin_tax_categories_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'zones' %>><%= link_to t("zones"), admin_zones_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'states' %>><%= link_to t("states"), admin_country_states_path(Spree::Config[:default_country_id]) %></li>
    <li<%== ' class="active"' if controller.controller_name == 'payment_methods' %>><%= link_to t("payment_methods"), admin_payment_methods_path %></li>
    <li<%== ' class="active"' if ['taxonomies', 'taxons'].include? controller.controller_name %>><%= link_to t("taxonomies"), admin_taxonomies_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'shipping_methods' %>><%= link_to t("shipping_methods"), admin_shipping_methods_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'inventory_settings' %>><%= link_to t("inventory_settings"), admin_inventory_settings_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'trackers' %>><%= link_to t("analytics_trackers"), admin_trackers_path %></li>
    <% end %>
    <li<%== ' class="active"' if controller.controller_name == 'configurations' %>><%= link_to t("complete_list"), admin_configurations_path %></li>
  </ul>

<% end %>

site/app/views/admin/shared/_destroy.js.erb
notice_div = $('.flash.notice');
<% notice = flash.delete(:notice)
if notice %>
  if (notice_div.length > 0) {
    notice_div.html("<%= notice %>");
    notice_div.show();
  } else {
    if ($("#content .toolbar").length > 0) {
      $("#content .toolbar").before('<div class="flash notice"><%= notice %></div>');
    } else {
      $("#content h1").before('<div class="flash notice"><%= notice %></div>');
    }
  } <%
end %>

<%= render(:partial => "/admin/shared/update_order_state") if @order %>

site/app/views/admin/shared/_edit_resource_links.html.erb
<p class="form-buttons">
  <%= button t("update") %>
  <%= t("or") %> <%= link_to t("cancel"), collection_url %>
</p>

site/app/views/admin/shared/_new_adjustment_button.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_adjustment"), new_admin_order_adjustment_url(@order), :icon => 'add' %>
    </li>
  </ul>
  <br class='clear' />
</div>

site/app/views/admin/shared/_new_resource_links.html.erb
<p class="form-buttons">
  <%= button t("actions.create") %>
  <%= t("or") %> <%= link_to t("actions.cancel"), collection_url %>
</p>

site/app/views/admin/shared/_order_details.html.erb
<%# This redirection is present ONLY to simplify overloading of the admin order summary format %>
<%= render :partial => 'shared/order_details', :locals => {:order => order} %>

site/app/views/admin/shared/_product_tabs.html.erb
<h1><%== t("editing_product") + " &ldquo;#{@product.name}&rdquo;" %></h1>

<% content_for :sidebar do %>

  <h3><%= @product.name %><span class='sku'><%= @product.sku %></span></h3>
  <br class="clear" />

  <ul class="sidebar product-menu">
    <%= hook :admin_product_tabs, {:current => current} do %>

      <li<%== ' class="active"' if current == "Product Details" %>>
        <%= link_to t("product_details"), edit_admin_product_url(@product) %>
      </li>
      <li<%== ' class="active"' if current == "Images" %>>
        <%= link_to t("images"), admin_product_images_url(@product) %>
      </li>
      <li<%== ' class="active"' if current == "Variants" %>>
        <%= link_to t("variants"),  admin_product_variants_url(@product)  %>
      </li>
      <li<%== ' class="active"' if current == "Option Types" %>>
        <%= link_to t("option_types"), selected_admin_product_option_types_url(@product) %>
      </li>
      <li<%== ' class="active"' if current == "Product Properties" %>>
        <%= link_to t("product_properties"), admin_product_product_properties_url(@product) %>
      </li>
      <li<%== ' class="active"' if current == "Taxons" %>>
        <%= link_to t("taxons"), selected_admin_product_taxons_url(@product) %>
      </li>

    <% end %>
  </ul>
  <br class="clear" />

<% end %>

site/app/views/admin/shared/_report_criteria.html.erb
<%= form_for @search, :url => sales_total_admin_reports_path  do |s| %>
    <label><%= t("date_range") %></label><br />
    <div class="yui-g date-range-filter">
      <div class="yui-u sub-field first">
        <%= s.spree_date_picker :created_at_greater_than %><br />
        <label class="sub"><%= t("start") %></label>
      </div>
      <div class="yui-u sub-field">
        <%= s.spree_date_picker :created_at_less_than %><br />
        <label><%= t("stop") %></label>
      </div>
    </div>

    <p><%= button t("search") %></p>
<% end %>

site/app/views/admin/shared/_show_resource_links.html.erb
<p class="actions">
<%= link_to t("edit"), edit_object_url %> |
<%= link_to t("back"), collection_url %> |
<%= link_to t("delete"), object_url, :confirm => t('are_you_sure_you_want_to_delete_this_record'), :method => :delete %>
</p>

site/app/views/admin/shared/_tabs.html.erb
<%= tab :overview, :route => :admin %>
<%= tab :orders, :payments, :creditcard_payments, :shipments, :creditcards, :return_authorizations %>
<%= tab :products , :option_types, :properties, :prototypes, :variants, :product_properties, :taxons %>
<%= tab :reports %>
<%= tab :configurations, :general_settings, :mail_methods, :tax_categories, :zones, :states, :payment_methods, :inventory_settings, :taxonomies, :shipping_methods, :trackers, :label => 'configuration' %>
<%= tab :users %>